### PR TITLE
Remove the spinning debug start icon

### PR DESCRIPTION
**Pull request by DominicVonk**

### CODE REVIEW

**Comment by EverlastEngineering** [comment]
Yeah.. that never worked so I guess I left it in by accident lol. Merged!

**Comment by DominicVonk** [comment]
Yeah I though so, thanks for the great extension. Check [My GitHub Action](https://github.com/DominicVonk/VSCode-Parameter-Hints/blob/master/.github/workflows/main.yml) for the automatic publish workflow 😄

**Comment by EverlastEngineering** [comment]
So I just drop that file in the right folder and it publishes to vsce? Sweet! Thanks!

**Comment by DominicVonk** [comment]
yeah you only need the: [VSCE_TOKEN](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) you may remove the ovsx one, it's for the other extension store.

**Pull request merged**
